### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by RienduPre** [jvmahon/homebridge-homeseer#12]
Any idea what might cause this? 

[2018-2-28 19:28:06] ====================                                                                                                                                                                  
[2018-2-28 19:28:06] ERROR LOADING PLUGIN homebridge-homeseer-plugin-2018:                                                                                                                                 
[2018-2-28 19:28:06] Error: Cannot find module '../build/Release/dns_sd_bindings'                                                                                                                          
    at Function.Module._resolveFilename (module.js:542:15)                                                                                                                                                 
    at Function.Module._load (module.js:472:25)                                                                                                                                                            
    at Module.require (module.js:585:17)                                                                                                                                                                   
    at require (internal/module.js:11:18)                                                                                                                                                                  
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-homeseer-plugin-2018/node_modules/mdns/lib/dns_sd.js:32:22)                                                                              
    at Module._compile (module.js:641:30)                                                                                                                                                                  
    at Object.Module._extensions..js (module.js:652:10)                                                                                                                                                    
    at Module.load (module.js:560:32)                                                                                                                                                                      
    at tryModuleLoad (module.js:503:12)                                                                                                                                                                    
    at Function.Module._load (module.js:495:3)                                                                                                                                                             
    at Module.require (module.js:585:17)                                                                                                                                                                   
    at require (internal/module.js:11:18)                                                                                                                                                                  
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-homeseer-plugin-2018/node_modules/mdns/lib/mdns.js:1:15)                                                                                 
    at Module._compile (module.js:641:30)                                                                                                                                                                  
    at Object.Module._extensions..js (module.js:652:10)                                                                                                                                                    
    at Module.load (module.js:560:32)                                                                                                                                                                      
[2018-2-28 19:28:06] ====================

**Comment by jvmahon** [comment]
This is typically a homebridge installation error, not a plugin error. I think it relates to a missing or incorrectly installed Bonjour or mDNS files. 

 

 

IF this is on Windows, look in the Bonjour section at the Wiki article: https://github.com/jvmahon/homebridge-homeseer/wiki/Installing-HomeBridge-on-Windows-10

 

IF this is Linux, did you do the step:

                sudo apt-get install libavahi-compat-libdnssd-dev

 

before you tried to install homebridge  and the plugin?  If you did that step after trying to install homebridge, you might have to do an uninstall of hombridge, then re-install it. i.e.,

                npm -g uninstall homebridge

                sudo apt-get install libavahi-compat-libdnssd-dev

                npm -g install --unsafe-perm homebridge

 

 

More info. on this error is at: https://github.com/nfarina/homebridge/issues/905

Some say you have to uninstall all the npm modules and then re-install each of them after making sure you installed the library libavahi-compat-libdnssd-dev

**Comment by RienduPre** [comment]
Don't think so.....

It only happens with 'your' plugin. If I uninstall your plugin the error is gone, if I install another plugin it starts without error.

So there must be something in the plugin which causes this.

I'm running on linux

**Comment by jvmahon** [comment]
What version of node are you using?

 

A Linux user recently reported that if node was less than 7, they had trouble with the plugin.

 

The only thing I can think of is that it does make use of native node Promises.  When I checked the nodejs info on the node web site, it indicated that version 4+ of node should be sufficient to support native Promises as I’ve used them, but it may be that I have to bump up the node version requirement in the packages file. I did all my testing on nodejs 8.9.4 and did not have the problem you mention.

 

Can you check this and let me know. Thanks.

**Comment by RienduPre** [comment]
Version 9.2.1

**Comment by jvmahon** [comment]
user rgerr in a Nov. 16 post in this thread:  https://github.com/nfarina/homebridge/issues/1609  Indicats that there may be a problem with Node 9 and then downgraded to 7.9 to fix the problem. Can you try using the 8.9.4 version of node? That's the version I've done all development / testing on. Otherwise, try to upgrade our node to the 9.7.0 release.

I'm just guessing here since I have never seen this problem, nor heard others report it, other than when the Unix lib that I mentioned was not installed.

If you still can’t get it to work, please try a 
	sudo npm rebuild --unsafe-perm
 
If none of this works, I can try switch the version of node on my system to see if I can replicate the error

**Comment by jvmahon** [comment]
Also, did you uninstall any versions of the 'original HomeSeer plugin. Check by doing:
npm -g ls --depth=0

You should see "homebridge-homeseer-plugin-2108"  but should not see "homebridge-homeseer-plugin";

**Comment by jvmahon** [comment]
I checked and, at least on Windows, Node 9.2.1 works. I went back and checked some other messages I received. Another Linux user who had a mdns error on a Raspberry Pi reported that the following steps cleared the error:

sudo apt-get install libavahi-compat-libdnssd-dev
sudo npm install -g --unsafe-perm homebridge
cd /usr/lib/node_modules/homebridge
sudo npm install --unsafe-perm mdns
sudo npm rebuild --unsafe-perm
sudo npm install -g homebridge-homeseer-plugin-2018

**Comment by AlanSmithe** [comment]
I had the same error with my linux build. 
npm -g uninstall homebridge-homeseer-plugin-2018
npm -g install --unsafe-perm homebridge-homeseer-plugin-2018
solved it for me

**Comment by RienduPre** [comment]
Hi,

After some extensive testing it seems to work very stable, I converted all my devices to your plugin now (except the alarm)

Thanks,
Rien

**Comment by jvmahon** [comment]
You're welcome. 
Note that I've added the alarm (SecuritySystem) support in version 2.3.6.
