### ISSUE TITLE
Error if router restarted

### ISSUE THREAD

**Issue by knaackville** [jvmahon/homebridge-homeseer#57]
Hi there.  I'm having an issue with homebridge/homeseer if and when my router restarts (error message below).  Both homebridge and homeseer are being run on the same windows machine if that matters.  I can get things going again by restarting homebridge, but is there a way around this?  Or is there an easy way that you've found to get homebridge to restart automatically if there is an error?  Thanks!

[2018-8-27 17:30:19] [HomeSeer] Poll # 891: Retrieved values for 16 HomeSeer devices.
[2018-8-27 17:30:21] [HomeSeer] * Warning * - Unable to connect to HomeSeer ASCII Port: 11000. Instant Status Not Enabled.
[2018-8-27 17:30:21] [HomeSeer] To enable ASCII Port / Instant Status, see WIKI "Instant Status" entry at:
[2018-8-27 17:30:21] [HomeSeer] https://github.com/jvmahon/homebridge-homeseer/wiki/Enable-Instant-Status-(HomeSeer-ASCII-Port)
[2018-8-27 17:30:22] [HomeSeer] * Warning * - ASCII Port closed - Instant Status Failure!. Restart system if failure continues.
dgram.js:600
    throw errnoException(err, 'setMulticastInterface');
    ^

Error: setMulticastInterface EADDRNOTAVAIL
    at _errnoException (util.js:1022:11)
    at Socket.setMulticastInterface (dgram.js:600:11)
    at Timeout.that.update [as _onTimeout] (C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge\node_modules\multicast-dns\index.js:141:12)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

**Comment by jvmahon** [comment]
I have not seen this before. I'll try to do some testing on my own router to see if I can replicate it.

**Comment by jvmahon** [comment]
One thought, in your config.json do you have the "host" line set as:

   "host": "http://127.0.0.1:80",

Or have you replaced the 127.0.0.1 with the actual network IP address? I.e., have you used something like:

     "host":"http://192.168.1.113:80"

If you have used the actual network IP address, you should replace that with the local loopback address 127.0.0.1 when both homebridge and homeseer are on the same computer.  This avoid homebridge having to use the router to resolve the address.

**Comment by villamann** [comment]
First of all I must once more express how great this plug-in is, thank you.
Second; I experience the same issue as described by knaackville. This is on a remote installation in my cabin. I`m running the HS3 Linux version together with Homebridge on a single Raspberry Pi. Whenever the router is restarted Homebridge cant connect to HS3. A restart of the Pi is required before connection is reestablished.
Before restart I get this line of error when obtaining the homebridge status:
_Attempting to re-start ASCII Port interface, Attempt 5723
* Warning * - Unable to connect to HomeSeer ASCII Port: 11000. Instant status not enabled._
I`m using 127.0.0.1 as host address.

**Comment by knaackville** [comment]
Doh, I should have thought of that!  You're right in that I was using my network IP for the address in the config.json.  Changing to the localhost 127.0.0.1 appears to have fixed the issue on a user-initiated reboot of my router and allowed homebridge to continue running.  If there are any further issues on my side (usually occurred over several days), I'll make an update to this.  

And thanks so much for the troubleshooting and the plugin itself!  This really has completed my home automation setup.

**Comment by jvmahon** [comment]
You're welcome. Glad its now working for you.
